//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ Compatible
// This file is automatically generated by RisohEditor.
// injector_res.rc

#define IDS_APPNAME                         100
#define IDS_CANTOPENPROCESS                 101
#define IDS_BITSDIFFER                      102
#define IDS_OUTOFMEMORY                     103
#define IDS_CANTMAKERTHREAD                 104
#define IDS_CANTSTARTPROCESS                105
#define IDS_INVALIDPID                      106
#define IDS_CANTFINDUNLOADER                107
#define IDS_CANTFINDLOADER                  108
#define IDS_INJECTIONFAIL                   109
#define IDS_REMOTETHREAD                    110
#define IDS_APC                             111
#define IDS_CANTGETTHREADS                  112
#define IDS_CANTUNINJECT                    113

#ifdef APSTUDIO_INVOKED
    #ifndef APSTUDIO_READONLY_SYMBOLS
        #define _APS_NO_MFC                 1
        #define _APS_NEXT_RESOURCE_VALUE    100
        #define _APS_NEXT_COMMAND_VALUE     100
        #define _APS_NEXT_CONTROL_VALUE     1000
        #define _APS_NEXT_SYMED_VALUE       300
    #endif
#endif
