//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ Compatible
// This file is automatically generated by RisohEditor.
// hookmaker_res.rc

#define IDC_STATIC                          (-1)

#define IDS_CANTFINDWONDERS                 100
#define IDS_CANTLOADWONDERS                 101
#define IDS_CANTWRITEHOOKBODY               102
#define IDS_INTERNALERROR                   103
#define IDS_ADDHOOKFUNCTIONS                104
#define IDS_HOOKBODYUPDATED                 105
#define IDS_APPNAME                         106
#define IDS_CANTFINDROSBE                   107
#define IDS_CANTOPENROSBE                   108
#define IDS_PAYLOADUPDATED                  109
#define IDS_PAYLOADBUILDFAIL                110
#define IDS_CANTFINDPAYLOAD                 111

#ifdef APSTUDIO_INVOKED
    #ifndef APSTUDIO_READONLY_SYMBOLS
        #define _APS_NO_MFC                 1
        #define _APS_NEXT_RESOURCE_VALUE    100
        #define _APS_NEXT_COMMAND_VALUE     100
        #define _APS_NEXT_CONTROL_VALUE     1000
        #define _APS_NEXT_SYMED_VALUE       300
    #endif
#endif
