/* This file is automatically generated by CustomHook hookmaker. */

typedef int (__stdcall *FN_MessageBoxW)(HWND, LPCWSTR, LPCWSTR, UINT);

static FN_MessageBoxW fn_MessageBoxW = NULL;

int __stdcall
DetourMessageBoxW(HWND p1, LPCWSTR p2, LPCWSTR p3, UINT p4)
{
    return (*fn_MessageBoxW)(p1, p2, p3, p4);
}

BOOL DoHook(BOOL bHook)
{
    if (bHook)
    {
        if (MH_CreateHookCast(&MessageBoxW, &DetourMessageBoxW, &fn_MessageBoxW) != MH_OK)
            return FALSE;
    }
    else
    {
        if (MH_RemoveHookCast(&MessageBoxW) != MH_OK)
            return FALSE;
    }
    return TRUE;
}

BOOL DoEnableHook(BOOL bEnable)
{
    if (bEnable)
    {
        if (MH_EnableHookCast(&MessageBoxW) != MH_OK)
            return FALSE;
    }
    else
    {
        if (MH_DisableHookCast(&MessageBoxW) != MH_OK)
            return FALSE;
    }
    return TRUE;
}

