#include <winsock2.h>
#include <windows.h>
#include <windowsx.h>
#include <vfw.h>

#include <accctrl.h>
#include <aclapi.h>
#include <aclui.h>
#include <assert.h>
#include <basetsd.h>
#include <basetyps.h>
#include <cguid.h>
#include <comcat.h>
#include <commctrl.h>
#include <commdlg.h>
#include <conio.h>
#include <control.h>
#include <cpl.h>
#include <cplext.h>
#include <ctype.h>
#include <custcntl.h>
#include <dbt.h>
#include <dir.h>
#include <direct.h>
#include <dirent.h>
#include <docobj.h>
#include <dos.h>
#include <dsgetdc.h>
#include <dsquery.h>
#include <dsrole.h>
#include <dvdevcod.h>
#include <edevdefs.h>
#include <errno.h>
#include <errors.h>
#include <evcode.h>
#include <exdisp.h>
#include <exdispid.h>
#include <fcntl.h>
#include <float.h>
#include <fltdefs.h>
#include <httpext.h>
#include <icm.h>
#include <idispids.h>
#include <imagehlp.h>
#include <initguid.h>
#include <intshcut.h>
#include <io.h>
#include <ipexport.h>
#include <iphlpapi.h>
#include <ipifcons.h>
#include <ipinfoid.h>
#include <iprtrmib.h>
#include <iptypes.h>
#include <ipxconst.h>
#include <ipxtfflt.h>
#include <isguids.h>
#include <ks.h>
#include <limits.h>
#include <lm.h>
#include <lmaccess.h>
#include <lmalert.h>
#include <lmapibuf.h>
#include <lmat.h>
#include <lmaudit.h>
#include <lmconfig.h>
#include <lmcons.h>
#include <lmerr.h>
#include <lmerrlog.h>
#include <lmmsg.h>
#include <lmremutl.h>
#include <lmrepl.h>
#include <lmserver.h>
#include <lmshare.h>
#include <lmsname.h>
#include <lmstats.h>
#include <lmsvc.h>
#include <lmuse.h>
#include <lmuseflg.h>
#include <lmwksta.h>
#include <locale.h>
#include <malloc.h>
#include <mapi.h>
#include <math.h>
#include <mbctype.h>
#include <mbstring.h>
#include <mciavi.h>
#include <mem.h>
#include <memory.h>
#include <mgm.h>
#include <mgmtapi.h>
#include <mlang.h>
#include <mmreg.h>
#include <mprapi.h>
#include <msacm.h>
#include <mshtml.h>
#include <nspapi.h>
#include <ntdsapi.h>
#include <ntsecapi.h>
#include <oaidl.h>
#include <objbase.h>
#include <objidl.h>
#include <objsafe.h>
#include <ocidl.h>
#include <odbcinst.h>
#include <ole2ver.h>
#include <oleacc.h>
#include <oleauto.h>
#include <olectl.h>
#include <oledlg.h>
#include <oleidl.h>
#include <pbt.h>
#include <process.h>
#include <prsht.h>
#include <psapi.h>
#include <ras.h>
#include <rasdlg.h>
#include <raserror.h>
#include <regstr.h>
#include <richedit.h>
#include <richole.h>
#include <rpcdce.h>
#include <rpcdcep.h>
#include <rpcndr.h>
#include <rpcnsi.h>
#include <rpcnsip.h>
#include <rpcnterr.h>
#include <rtutils.h>
#include <schannel.h>
#include <schnlsp.h>
#include <scrnsave.h>
#include <sddl.h>
#include <search.h>
#include <servprov.h>
#include <setjmp.h>
#include <setupapi.h>
#include <share.h>
#include <shldisp.h>
#include <shlguid.h>
#include <shlobj.h>
#include <shlwapi.h>
#include <signal.h>
#include <snmp.h>
#include <sql.h>
#include <sqlext.h>
#include <sqltypes.h>
#include <sqlucode.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <svcguid.h>
#include <tchar.h>
#include <time.h>
#include <tlhelp32.h>
#include <unknwn.h>
#include <userenv.h>
#include <usp10.h>
#include <utime.h>
#include <wchar.h>
#include <wctype.h>
#include <winable.h>
#include <winerror.h>
#include <wininet.h>
#include <winioctl.h>
#include <winldap.h>
#include <winnls.h>
#include <winreg.h>
#include <ws2spi.h>
#include <ws2tcpip.h>
#include <wsipx.h>
#include <wsnetbs.h>
#include <wtsapi32.h>
#include <wtypes.h>
